### ISSUE TITLE
Fatal error upon initial submit

### ISSUE THREAD

**Issue by SteinarVP** [vladim0105/Twitter-Analyzer#11]
![image](https://user-images.githubusercontent.com/5860460/68081944-fdc69700-fe50-11e9-97f9-9c1d8aee6394.png)
Some times submitting a search will cause this error, freezing the program in forever loading, requiring restart. Seems to occur more often if submission was done quickly after opening program.

**Comment by vladim0105** [comment]
This happens due to the user searching for a twitter handle before the Twitter API has provided the program the authorization key. Essentially, this means that the program is not able to fetch tweets for the first milliseconds (depends on connection speed etc.).

One solution is to just disable searching until the program has received the authorization key.
